openapi: "3.0.1"
info:
  title: "streaming-lambda-api"
  version: "1.0.0"
paths:
  /ask:
    post:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/HomeHelloRequest"
                - $ref: "#/components/schemas/WorkRequest"
                - $ref: "#/components/schemas/CircleNewRequest"
                - $ref: "#/components/schemas/UserbuyPage1Request"
                - $ref: "#/components/schemas/CartListRequest"
                - $ref: "#/components/schemas/DownloadListRequest"
              discriminator:
                propertyName: usecase
                mapping:
                  "home:hello": "#/components/schemas/HomeHelloRequest"
                  "work": "#/components/schemas/WorkRequest"
                  "circle:new": "#/components/schemas/CircleNewRequest"
                  "userbuy:page1": "#/components/schemas/UserbuyPage1Request"
                  "cart:list": "#/components/schemas/CartListRequest"
                  "download:list": "#/components/schemas/DownloadListRequest"

      responses:
        "200":
          description: "Streaming response from agent"
          content:
            text/plain:
              schema:
                type: string
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2021-11-15/functions/${StreamingResponseFunction.Arn}/response-streaming-invocations"
        httpMethod: "POST"
        responseTransferMode: "STREAM"
        type: "aws_proxy"
      security:
        - api_key: []
    options:
      responses:
        200:
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content: {}
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: '{"statusCode": 200}'
        passthroughBehavior: "never"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
      security: []
components:
  schemas:
    HomeHelloRequest:
      type: object
      additionalProperties: false
      properties:
        characterId:
          type: string
          enum: ["default"]
        usecase:
          type: string
          enum: ["home:hello"]
        payload:
          $ref: "#/components/schemas/HomeHelloPayload"
      required:
        - characterId
        - usecase
        - payload

    WorkRequest:
      type: object
      additionalProperties: false
      properties:
        characterId:
          type: string
          enum: ["default"]
        usecase:
          type: string
          enum: ["work"]
        payload:
          $ref: "#/components/schemas/WorkPayload"
      required:
        - characterId
        - usecase
        - payload

    CircleNewRequest:
      type: object
      additionalProperties: false
      properties:
        characterId:
          type: string
          enum: ["default"]
        usecase:
          type: string
          enum: ["circle:new"]
        payload:
          $ref: "#/components/schemas/CircleNewPayload"
      required:
        - characterId
        - usecase
        - payload

    UserbuyPage1Request:
      type: object
      additionalProperties: false
      properties:
        characterId:
          type: string
          enum: ["default"]
        usecase:
          type: string
          enum: ["userbuy:page1"]
        payload:
          $ref: "#/components/schemas/UserbuyPage1Payload"
      required:
        - characterId
        - usecase
        - payload

    CartListRequest:
      type: object
      additionalProperties: false
      properties:
        characterId:
          type: string
          enum: ["default"]
        usecase:
          type: string
          enum: ["cart:list"]
        payload:
          $ref: "#/components/schemas/CartListPayload"
      required:
        - characterId
        - usecase
        - payload

    DownloadListRequest:
      type: object
      additionalProperties: false
      properties:
        characterId:
          type: string
          enum: ["default"]
        usecase:
          type: string
          enum: ["download:list"]
        payload:
          $ref: "#/components/schemas/DownloadListPayload"
      required:
        - characterId
        - usecase
        - payload

    HomeHelloPayload:
      type: object
      additionalProperties: false
      properties:
        floor:
          type: string
      required:
        - floor

    WorkPayload:
      type: object
      additionalProperties: false
      properties:
        work:
          $ref: "#/components/schemas/Work"
      required:
        - work

    CircleNewPayload:
      type: object
      additionalProperties: false
      properties:
        makerName:
          type: string
        circleAnnounceWorkList:
          type: array
          items:
            $ref: "#/components/schemas/CircleAnnounceWork"
        circleWorkList:
          type: array
          items:
            $ref: "#/components/schemas/CircleWork"
      required:
        - makerName
        - circleAnnounceWorkList
        - circleWorkList

    UserbuyPage1Payload:
      type: object
      additionalProperties: false
      properties:
        userbuyWorkList:
          type: array
          items:
            $ref: "#/components/schemas/UserbuyWork"
      required:
        - userbuyWorkList

    CartListPayload:
      type: object
      additionalProperties: false
      properties:
        cartWorkList:
          type: array
          items:
            $ref: "#/components/schemas/CartWork"
        totalDiscount:
          type: string
        totalOriginal:
          type: string
          nullable: true
        couponName:
          type: string
          nullable: true
        totalCoupon:
          type: string
          nullable: true
        pricePrefix:
          type: string
        priceSuffix:
          type: string
      required:
        - cartWorkList
        - totalDiscount
        - totalOriginal
        - couponName
        - totalCoupon
        - pricePrefix
        - priceSuffix

    DownloadListPayload:
      type: object
      additionalProperties: false
      properties:
        downloadWorkList:
          type: array
          items:
            $ref: "#/components/schemas/DownloadWork"
      required:
        - downloadWorkList

    EmptyPayload:
      type: object
      additionalProperties: false
      maxProperties: 0

    Work:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        makerName:
          type: string
        price:
          type: string
        officialPrice:
          type: string
        couponPrice:
          type: string
          nullable: true
        pricePrefix:
          type: string
        priceSuffix:
          type: string
        genres:
          type: array
          items:
            type: string
        description:
          type: string
      required:
        - name
        - makerName
        - price
        - officialPrice
        - pricePrefix
        - priceSuffix
        - genres
        - description

    CircleWork:
      type: object
      additionalProperties: false
      properties:
        productId:
          type: string
        category:
          type: string
        name:
          type: string
        author:
          type: string
          nullable: true
        price:
          type: string
        officialPrice:
          type: string
        pricePrefix:
          type: string
        priceSuffix:
          type: string
        labels:
          type: array
          items:
            type: string
      required:
        - productId
        - category
        - name
        - author
        - price
        - officialPrice
        - pricePrefix
        - priceSuffix
        - labels

    CircleAnnounceWork:
      type: object
      additionalProperties: false
      properties:
        productId:
          type: string
        name:
          type: string
        author:
          type: string
          nullable: true
        category:
          type: string
        expectedDate:
          type: string
        freeSample:
          type: boolean
      required:
        - productId
        - name
        - author
        - category
        - expectedDate
        - freeSample

    UserbuyWork:
      type: object
      additionalProperties: false
      properties:
        productId:
          type: string
        buyDate:
          type: string
        name:
          type: string
        makerName:
          type: string
        genres:
          type: array
          items:
            type: string
        price:
          type: string
        pricePrefix:
          type: string
        priceSuffix:
          type: string
      required:
        - productId
        - buyDate
        - name
        - makerName
        - genres
        - price
        - pricePrefix
        - priceSuffix

    CartWork:
      type: object
      additionalProperties: false
      properties:
        productId:
          type: string
        name:
          type: string
        makerName:
          type: string
        category:
          type: string
        price:
          type: string
        officialPrice:
          type: string
      required:
        - productId
        - name
        - makerName
        - category
        - price
        - officialPrice

    DownloadWork:
      type: object
      additionalProperties: false
      properties:
        productId:
          type: string
        name:
          type: string
        makerName:
          type: string
        genre:
          type: string
      required:
        - productId
        - name
        - makerName
        - genre
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
x-amazon-apigateway-api-key-source: HEADER
